CREATE TABLE questions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    item_number INT NOT NULL UNIQUE,
    question TEXT NOT NULL,
    choices JSON NOT NULL,
    correct_answer CHAR(1) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP NULL DEFAULT NULL
);